# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPBv9jbnL4GTreQcyiMQu8Xf-_YzcjgR
"""

from google.colab import files
uploaded = files.upload()  # click and select your FL_CarbonAware_Upgrade.zip

import zipfile, os

with zipfile.ZipFile('FL_CarbonAware_Upgrade.zip', 'r') as z:
    z.extractall('/content/fl_upgrade')

os.chdir('/content/fl_upgrade')
!ls  # confirm all files are there

import os
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

# Use newer flwr that supports Python 3.12 + newer ray
!pip install -q "flwr[simulation]>=1.11.0"
!pip install -q torch torchvision pandas matplotlib numpy
!pip install -q "protobuf>=6.31.1"

# Verify
import google.protobuf
import flwr
import torch
print(f"protobuf : {google.protobuf.__version__}")
print(f"flwr     : {flwr.__version__}")
print(f"torch    : {torch.__version__}")
print(f"GPU      : {torch.cuda.is_available()} — {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'none'}")
print("\n✅ Ready")

import os
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
# DO NOT set FLOWER_CLIENT_DEVICE here — simulation.py handles it
print("✅ Environment variables set")

with open('/content/fl_upgrade/client.py', 'r') as f:
    content = f.read()

content = content.replace(
    '_CLIENT_DEVICE = torch.device("cpu")',
    '_CLIENT_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")'
)

with open('/content/fl_upgrade/client.py', 'w') as f:
    f.write(content)

print("✅ client.py patched — clients will use GPU if available")

# ── COMPLETE PATCH — run this single cell ────────────────────────────────────

with open('/content/fl_upgrade/simulation.py', 'r') as f:
    content = f.read()

# Fix 1: Set NUM_ROUNDS to 100
content = content.replace('NUM_ROUNDS        = 30', 'NUM_ROUNDS        = 100')
content = content.replace('NUM_ROUNDS = 30',         'NUM_ROUNDS = 100')

# Fix 2: Remove CPU lock
content = content.replace('os.environ["FLOWER_CLIENT_DEVICE"]       = "cpu"', '')
content = content.replace('os.environ["FLOWER_CLIENT_DEVICE"] = "cpu"',       '')

# Fix 3: Add protobuf + OpenMP fixes at top
header = '''import os
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

'''
if "PROTOCOL_BUFFERS" not in content:
    content = header + content

# Fix 4: Update evaluate_global_model to use GPU
old_eval = '''def evaluate_global_model(parameters) -> float:
    model = Net()
    model.load_state_dict(
        {k: torch.tensor(v) for k, v in zip(model.state_dict().keys(), parameters)},
        strict=True)
    model.eval()
    correct = total = 0
    with torch.no_grad():
        for x, y in TESTLOADER:
            correct += (model(x).argmax(1) == y).sum().item()
            total   += y.size(0)
    return correct / max(total, 1)'''

new_eval = '''_SERVER_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Server device: {_SERVER_DEVICE}")

def evaluate_global_model(parameters) -> float:
    model = Net().to(_SERVER_DEVICE)
    model.load_state_dict(
        {k: torch.tensor(v).to(_SERVER_DEVICE)
         for k, v in zip(model.state_dict().keys(), parameters)},
        strict=True)
    model.eval()
    correct = total = 0
    with torch.no_grad():
        for x, y in TESTLOADER:
            x, y = x.to(_SERVER_DEVICE), y.to(_SERVER_DEVICE)
            correct += (model(x).argmax(1) == y).sum().item()
            total   += y.size(0)
    return correct / max(total, 1)'''

if '_SERVER_DEVICE' not in content:
    content = content.replace(old_eval, new_eval)

# Fix 5: Update Ray resources for L4 GPU
old_resources = 'client_resources={"num_cpus": 1, "num_gpus": 0.0},\n        ray_init_args={"num_cpus": 2, "num_gpus": 0,\n                       "include_dashboard": False, "ignore_reinit_error": True},'
new_resources = 'client_resources={"num_cpus": 2, "num_gpus": 0.1},\n        ray_init_args={"num_cpus": 4, "num_gpus": 1,\n                       "include_dashboard": False, "ignore_reinit_error": True},'

content = content.replace(old_resources, new_resources)

with open('/content/fl_upgrade/simulation.py', 'w') as f:
    f.write(content)

print("✅ simulation.py fully patched")

# ── VERIFY ────────────────────────────────────────────────────────────────────
import re, torch

with open('/content/fl_upgrade/simulation.py', 'r') as f:
    s = f.read()

checks = {
    "NUM_ROUNDS = 100":           "NUM_ROUNDS        = 100" in s or "NUM_ROUNDS = 100" in s,
    "CPU lock removed":           'FLOWER_CLIENT_DEVICE" = "cpu"' not in s,
    "protobuf fix present":       "PROTOCOL_BUFFERS" in s,
    "GPU eval present":           "_SERVER_DEVICE" in s,
    "Ray GPU resources":          'num_gpus": 0.1' in s,
}

all_pass = True
for name, result in checks.items():
    status = "✅" if result else "❌"
    if not result: all_pass = False
    print(f"  {status}  {name}")

with open('/content/fl_upgrade/client.py', 'r') as f:
    c = f.read()
client_gpu = 'cuda' in c and '_CLIENT_DEVICE = torch.device("cpu")' not in c
print(f"  {'✅' if client_gpu else '❌'}  client.py GPU enabled")

print(f"\n  GPU: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NOT FOUND'}")
print(f"\n{'✅ ALL CHECKS PASSED — ready to run' if all_pass and client_gpu else '❌ SOME CHECKS FAILED — do not run yet'}")

with open('/content/fl_upgrade/simulation.py', 'r') as f:
    content = f.read()

old_resources = 'client_resources={"num_cpus": 1, "num_gpus": 0.0},\n        ray_init_args={"num_cpus": 2, "num_gpus": 0,\n                       "include_dashboard": False, "ignore_reinit_error": True},'

new_resources = 'client_resources={"num_cpus": 2, "num_gpus": 0.1},\n        ray_init_args={"num_cpus": 4, "num_gpus": 1,\n                       "include_dashboard": False, "ignore_reinit_error": True},'

count = content.count(old_resources)
print(f"Found {count} occurrences to replace")

content = content.replace(old_resources, new_resources)

with open('/content/fl_upgrade/simulation.py', 'w') as f:
    f.write(content)

print("✅ Ray resources patched")

import torch

# Check client.py
with open('/content/fl_upgrade/client.py', 'r') as f:
    c = f.read()
assert 'cuda' in c, "❌ client.py GPU patch missing"
assert '_CLIENT_DEVICE = torch.device("cpu")' not in c, "❌ client.py still locked to CPU"
print("✅ client.py — GPU enabled")

# Check simulation.py
with open('/content/fl_upgrade/simulation.py', 'r') as f:
    s = f.read()
assert '_SERVER_DEVICE' in s,        "❌ server GPU device missing"
assert 'num_gpus": 0.1' in s,        "❌ Ray GPU resources missing"
assert 'FLOWER_CLIENT_DEVICE" = "cpu"' not in s, "❌ CPU lock still present"
assert 'PROTOCOL_BUFFERS' in s,      "❌ protobuf fix missing"
print("✅ simulation.py — GPU eval + 0.1 GPU per client + protobuf fix")

# Check GPU
print(f"\n✅ GPU available : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"   GPU name     : {torch.cuda.get_device_name(0)}")
    print(f"   VRAM         : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB")
else:
    print("   ⚠️ No GPU — check Runtime → Change runtime type → L4 GPU")

import os
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
os.chdir('/content/fl_upgrade')
!python simulation.py

import zipfile
from google.colab import files

with zipfile.ZipFile('upgrade_results.zip', 'w') as z:
    for f in os.listdir('results/'):
        z.write(f'results/{f}')

files.download('upgrade_results.zip')